### ISSUE TITLE
安装后页面不显示版本号及自定义代码不生效

### ISSUE THREAD

**Issue by changeCat** [vfhky/serv00_ct8_nezha#10]
大佬这个是bug吗，安装后页面应该显示版本号的地方显示debug，后台管理中 设置了  自定义代码（样式和脚本）不生效，前面serv00安装的，后面虚拟机装的
![image](https://github.com/user-attachments/assets/e619329b-447d-4285-a822-870399a673c4)

**Comment by vfhky** [comment]
> 大佬这个是bug吗，安装后页面应该显示版本号的地方显示debug，后台管理中 设置了 自定义代码（样式和脚本）不生效，前面serv00安装的，后面虚拟机装的 ![image](https://private-user-images.githubusercontent.com/14162279/397651840-e619329b-447d-4285-a822-870399a673c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTY0ODgsIm5iZiI6MTczNDY5NjE4OCwicGF0aCI6Ii8xNDE2MjI3OS8zOTc2NTE4NDAtZTYxOTMyOWItNDQ3ZC00Mjg1LWE4MjItODcwMzk5YTY3M2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDEyMDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzdmODcyM2JjMmUxYTVmODY0NTk1ODYyNjA2ZGQ3YzYwNGE3NTNiZDk2MDBhNDBhZTM1MjhiNTU2YjgwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6MT6JtopkwlG1cJvuQo-5E56oH7bB-tFXGoYfcI0HNg)

我确认下

**Comment by Kiritocyz** [comment]
> 大佬这个是bug吗，安装后页面应该显示版本号的地方显示debug，后台管理中 设置了 自定义代码（样式和脚本）不生效，前面serv00安装的，后面虚拟机装的 ![image](https://private-user-images.githubusercontent.com/14162279/397651840-e619329b-447d-4285-a822-870399a673c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzc4OTEsIm5iZiI6MTczNDkzNzU5MSwicGF0aCI6Ii8xNDE2MjI3OS8zOTc2NTE4NDAtZTYxOTMyOWItNDQ3ZC00Mjg1LWE4MjItODcwMzk5YTY3M2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3MDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YjU2MTRmMzQ2MDBlN2Y3MGE0MDMyNzRkMjk0NDNmOWM0Y2M3NWY3YTc3ZTNhZjhjM2FhZGVhNjZlMDM2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UauFxa2c2g4nOZVZAbM0nPVaRTF7emMs8-3PBblqDck)

我昨天安装，今天弄美化也遇到了，鼠标特效有，其他和你图里标注的一样，我感觉是这个主题没更新导致的？

**Comment by vfhky** [comment]
@changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。

**Comment by Kiritocyz** [comment]
> @changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。

好耶！🥳感谢大佬！😘

**Comment by vfhky** [comment]
> > @changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。
> 
> 好耶！🥳感谢大佬！😘

感谢反馈

**Comment by changeCat** [comment]
> > > @changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。
> > 
> > 
> > 好耶！🥳感谢大佬！😘
> 
> 感谢反馈

感谢大佬解决

**Comment by vfhky** [comment]
> > > > @changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。
> > > 
> > > 
> > > 好耶！🥳感谢大佬！😘
> > 
> > 
> > 感谢反馈
> 
> 感谢大佬解决

你们测试正常的吗？我看有版本号，没有用过自定义代码

**Comment by Kiritocyz** [comment]
> > > > > @changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。
> > > > 
> > > > 
> > > > 好耶！🥳感谢大佬！😘
> > > 
> > > 
> > > 感谢反馈
> > 
> > 
> > 感谢大佬解决
> 
> 你们测试正常的吗？我看有版本号，没有用过自定义代码

![image](https://github.com/user-attachments/assets/2549bbf7-987c-472b-83d3-3b7c358d0f85)
背景和小人都出现了，版本号都更新了。目前正常

**Comment by vfhky** [comment]
> > > > > > @changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。
> > > > > 
> > > > > 
> > > > > 好耶！🥳感谢大佬！😘
> > > > 
> > > > 
> > > > 感谢反馈
> > > 
> > > 
> > > 感谢大佬解决
> > 
> > 
> > 你们测试正常的吗？我看有版本号，没有用过自定义代码
> 
> ![image](https://private-user-images.githubusercontent.com/62319762/398351484-2549bbf7-987c-472b-83d3-3b7c358d0f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjYxMTgsIm5iZiI6MTczNTAyNTgxOCwicGF0aCI6Ii82MjMxOTc2Mi8zOTgzNTE0ODQtMjU0OWJiZjctOTg3Yy00NzJiLTgzZDMtM2I3YzM1OGQwZjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA3MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YjYxNDNmZTc4NTkxZmU5ZWMzNzA1OTc3NDFiNjVmYzg3YmFkYjZmODlmMTA2OTYzYzgzODM0Yjc5ZjlkNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BqMQusmNHRMxMom48TlqjQimwTdG6FYZDwdO4-vT1OU) 背景和小人都出现了，版本号都更新了。目前正常

这个背景可以

**Comment by vfhky** [comment]
没啥问题的话，麻烦顺手close一下这个issue吧

**Comment by changeCat** [comment]
> > > > > > @changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。
> > > > > 
> > > > > 
> > > > > 好耶！🥳感谢大佬！😘
> > > > 
> > > > 
> > > > 感谢反馈
> > > 
> > > 
> > > 感谢大佬解决
> > 
> > 
> > 你们测试正常的吗？我看有版本号，没有用过自定义代码
> 
> ![image](https://private-user-images.githubusercontent.com/62319762/398351484-2549bbf7-987c-472b-83d3-3b7c358d0f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDQ5NzQsIm5iZiI6MTczNTA0NDY3NCwicGF0aCI6Ii82MjMxOTc2Mi8zOTgzNTE0ODQtMjU0OWJiZjctOTg3Yy00NzJiLTgzZDMtM2I3YzM1OGQwZjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEyNTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZjUyMjllNzY2YmNmZWFjNjI3NmVlZjYwMWQ2ZWU2NjU0MDdmNmQzNzNjZjQ2MWU2MDQxYWYzYTg2Mjk1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cqV_JQgSrIQYnK5Xe5oeUab2DVv5h6OEP9hW_q2ykoU) 背景和小人都出现了，版本号都更新了。目前正常

你背景图片咋设置的，我设置了还是不生效

**Comment by Kiritocyz** [comment]
> > > > > > > @changeCat @Kiritocyz 问题已经修复，请升级到最新版本即可。
> > > > > > 
> > > > > > 
> > > > > > 好耶！🥳感谢大佬！😘
> > > > > 
> > > > > 
> > > > > 感谢反馈
> > > > 
> > > > 
> > > > 感谢大佬解决
> > > 
> > > 
> > > 你们测试正常的吗？我看有版本号，没有用过自定义代码
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/62319762/398351484-2549bbf7-987c-472b-83d3-3b7c358d0f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDQ5NzQsIm5iZiI6MTczNTA0NDY3NCwicGF0aCI6Ii82MjMxOTc2Mi8zOTgzNTE0ODQtMjU0OWJiZjctOTg3Yy00NzJiLTgzZDMtM2I3YzM1OGQwZjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEyNTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZjUyMjllNzY2YmNmZWFjNjI3NmVlZjYwMWQ2ZWU2NjU0MDdmNmQzNzNjZjQ2MWU2MDQxYWYzYTg2Mjk1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cqV_JQgSrIQYnK5Xe5oeUab2DVv5h6OEP9hW_q2ykoU) 背景和小人都出现了，版本号都更新了。目前正常
> 
> 你背景图片咋设置的，我设置了还是不生效

更新本项目代码并升级面板到最新版本
