### ISSUE TITLE
请问如何保活和重启呢

### ISSUE THREAD

**Issue by doubleJazzCat** [vfhky/serv00_ct8_nezha#11]
一键安装面板和agent, 今天一看进程被干掉了
![image](https://github.com/user-attachments/assets/c977ea68-07a1-41cb-832d-ec1cc0e9e5a6)

**Comment by vfhky** [comment]
> 运行 bash heart_beat_entry.sh 会添加crontab

一台serv00机器是可能会被kill掉的，探针进程保活全靠这个cron检查和重新拉起进程。

要么你就安装多台，这样主机之前能实现相互保活。

要么你在其它非serv00/CT8的机器上加一个定时任务，例如：https://typecodes.com/python/serv00ct8nezha3.html
