### ISSUE TITLE
大佬，serv00只装agent ，cloudflare 开小云朵连不上。

### ISSUE THREAD

**Issue by terryzung** [vfhky/serv00_ct8_nezha#12]
cloudflare开小云朵连不上，其他vps通过后台命令安装可以连接上。

**Comment by vfhky** [comment]
先在serv00上Telnet下CF域名端口，看看输出
或者把serv00机器上的agent的config.yaml中的debug为true，然后执行nezha-agent -c config.yml 可以看到具体的debug日志

**Comment by vfhky** [comment]
对了，你安装的时候有没有开启 tls ？

**Comment by terryzung** [comment]
开启了tls 用的443端口

**Comment by terryzung** [comment]
面板端用的nginx proxy manager反代了8008端口

**Comment by vfhky** [comment]
> 先在serv00上Telnet下CF域名端口，看看输出 或者把serv00机器上的agent的config.yaml中的debug为true，然后执行nezha-agent -c config.yml 可以看到具体的debug日志

那按照这个操作下

**Comment by terryzung** [comment]
03:18:22 NEZHA@2024-12-25 03:18:22>> 上报系统信息失败: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large"
I: 03:18:22 NEZHA@2024-12-25 03:18:22>> Error to close connection ...

**Comment by terryzung** [comment]
同时debug日志提示更新失败
03:18:22 NEZHA@2024-12-25 03:18:22>> 检查更新: 1.4.0
I: 03:18:22 NEZHA@2024-12-25 03:18:22>> 更新失败: GET https://api.github.com/repos/nezhahq/agent/releases: 403 API rate limit exceeded for 65.21.206.30. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 18m02s]

**Comment by vfhky** [comment]
> 同时debug日志提示更新失败 03:18:22 NEZHA@2024-12-25 03:18:22>> 检查更新: 1.4.0 I: 03:18:22 NEZHA@2024-12-25 03:18:22>> 更新失败: GET https://api.github.com/repos/nezhahq/agent/releases: 403 API rate limit exceeded for 65.21.206.30. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 18m02s]

这个影响不大，用于更新的

**Comment by vfhky** [comment]
> 03:18:22 NEZHA@2024-12-25 03:18:22>> 上报系统信息失败: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large" I: 03:18:22 NEZHA@2024-12-25 03:18:22>> Error to close connection ...

这个异常是关键，得看看

**Comment by vfhky** [comment]
@terryzung 到serv00的agent目录执行下命令 grep -a "tls" config.yml ，看看输出

**Comment by terryzung** [comment]
insecure_tls: true
tls: false

**Comment by vfhky** [comment]
> tls

应该是这个原因：tls 也要为ture

**Comment by terryzung** [comment]
是的，可以了，把config.yml里面tls改为true就连接上了。但是安装配置时有打开tls的，那个tls是insecure_tls？

**Comment by vfhky** [comment]
> 是的，可以了，把config.yml里面tls改为true就连接上了。但是安装配置时有打开tls的，那个tls是insecure_tls？

晚点我确认下是不是安装脚本的bug，只修改了insecure_tls，没有修改tls

**Comment by vfhky** [comment]
@terryzung 代码bug，已经修复了。麻烦帮忙验证一下：在serv00上完全删除已经安装的agent目录（包含所有文件），然后git pull更新安装代码，再安装一遍agent看看

**Comment by terryzung** [comment]
用一个干净的装了，没有问题。
