### ISSUE TITLE
七牛备份不生效

### ISSUE THREAD

**Issue by Kiritocyz** [vfhky/serv00_ct8_nezha#13]
![image](https://github.com/user-attachments/assets/b88b1227-b243-4901-84c5-4f0f66338c7a)

#### 我已经在sys.eg中和sys.conf中开启了七牛备份的功能并添加了密钥。  

跟据博客五的描述，只需要在安装了面板的机子上开启，且图片显示七牛备份是在心跳模块中触发。

但是在host.eg中添加本机的信息，运行python3 main.py，输出信息里说心跳模块会跳过本机。

然后自动生成的heartbeat.eg和heartbeat.conf中均没有本机信息，且运行heart_beat_entry.sh也未输出七牛备份信息。

**Comment by vfhky** [comment]
grep -a "ENABLE_QINIU_BACKUP" sys.conf 看看输出

**Comment by Kiritocyz** [comment]
> grep -a "ENABLE_QINIU_BACKUP" sys.conf 看看输出

![image](https://github.com/user-attachments/assets/d1afb960-21e3-4d14-8744-c33287775aa8)
这个没问题，内容是我亲手更改的

**Comment by Kiritocyz** [comment]
> grep -a "ENABLE_QINIU_BACKUP" sys.conf 看看输出

![image](https://github.com/user-attachments/assets/85d0e27f-53ab-4c8c-b0d0-d19002e83fff)
我终于找到日志了，原来会创建新的bucket，我去改一下😭
