### ISSUE TITLE
第一次安装dashboard失败

### ISSUE THREAD

**Issue by jiangyanning123** [vfhky/serv00_ct8_nezha#4]
是否安装哪吒dashboard? (Y/y 执行，N/n 不执行): y
===> 开始安装哪吒dashboard....
当前最新版本为: v0.19.20
===> [dashboard] https://github.com/vfhky/nezha-build/releases/download/v0.19.20/nezha-dashboard.zip 下载失败，请检查是否能正常访问

**Comment by jiangyanning123** [comment]
可以下载出来

**Comment by vfhky** [comment]
那你重新安装一下，有时是会访问不了github

**Comment by jiangyanning123** [comment]
重新安装还是不行，还是出现一样的错误

**Comment by vfhky** [comment]
这么奇怪。。我确认下看看

**Comment by vfhky** [comment]
> 重新安装还是不行，还是出现一样的错误

上将修复主机图标引入的问题，已修复，git pull 更新下代码再试下

**Comment by jiangyanning123** [comment]
问题解决了，下载完成

**Comment by vfhky** [comment]
> 问题解决了，下载完成

好的。。没其它问题了的话麻烦close一下
