### ISSUE TITLE
这个报错是正常的吗？

### ISSUE THREAD

**Issue by licoba** [vfhky/serv00_ct8_nezha#5]
![image](https://github.com/user-attachments/assets/e879e687-0801-4e22-bb87-75f7af02a418)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

**Comment by licoba** [comment]
搭建完成了，访问面板的地址又是啥呢？

**Comment by vfhky** [comment]
上面报错应该是Python包冲突，应该没关系。面板地址你可以用serv00给你的，也可以用自己私有的域名指向serv00
