### ISSUE TITLE
agent连不上dashboard

### ISSUE THREAD

**Issue by doubleJazzCat** [vfhky/serv00_ct8_nezha#8]
dashboard在端口8800
在Websites代理出去可以访问

grpc端口在8801
agent的server填xxxx.serv00.net:8801
结果连不上, 请问是哪里做错了吗

**Comment by vfhky** [comment]
> dashboard在端口8800 在Websites代理出去可以访问
> 
> grpc端口在8801 agent的server填xxxx.serv00.net:8801 结果连不上, 请问是哪里做错了吗

你是安装的v0？

**Comment by doubleJazzCat** [comment]
> > dashboard在端口8800 在Websites代理出去可以访问
> > grpc端口在8801 agent的server填xxxx.serv00.net:8801 结果连不上, 请问是哪里做错了吗
> 
> 你是安装的v0？

安的v1, 脚本也有grpc这个选项

**Comment by vfhky** [comment]
> > > dashboard在端口8800 在Websites代理出去可以访问
> > > grpc端口在8801 agent的server填xxxx.serv00.net:8801 结果连不上, 请问是哪里做错了吗
> > 
> > 
> > 你是安装的v0？
> 
> 安的v1, 脚本也有grpc这个选项

v1共用dashboard的端口的，不需要两个

**Comment by strail6** [comment]
今天突然进不去面板了

**Comment by vfhky** [comment]
> 今天突然进不去面板了

看看dashboard进程还在不在

**Comment by doubleJazzCat** [comment]
@vfhky 问题解决了, 感谢
大佬有没有波兰的机器呢, 我拿s15和你换

**Comment by strail6** [comment]
> > 今天突然进不去面板了
> 
> 查看仪表板进程还在

这个要发送什么命令呀

**Comment by vfhky** [comment]
> > > 今天突然进不去面板了
> > 
> > 
> > 查看仪表板进程还在
> 
> 这个要发送什么命令呀

ps ux| grep nezha  看看。估计你是只安装了一台机器，无法多主机相互保活。

**Comment by strail6** [comment]
> > > > 今天突然进不去面板了
> > > 
> > > 
> > > 查看仪表板进程还在
> > 
> > 
> > 这个要发送什么命令呀
> 
> ps ux| grep nezha 看看。估计你是只安装了一台机器，无法多主机相互保活。

strail 43349  0.0  0.0   432   256 1430  RN+  15:06   0:00.00 grep nezha
显示这个

**Comment by doubleJazzCat** [comment]
> > > > > 今天突然进不去面板了
> > > > 
> > > > 
> > > > 查看仪表板进程还在
> > > 
> > > 
> > > 这个要发送什么命令呀
> > 
> > 
> > ps ux| grep nezha 看看。估计你是只安装了一台机器，无法多主机相互保活。
> 
> strail 43349 0.0 0.0 432 256 1430 RN+ 15:06 0:00.00 grep nezha 显示这个

那说明你服务挂了, 你可以参考参考我的
第1, 3条是我跑了两个agent
第2条是面板
第4条是当前的查询指令

![image](https://github.com/user-attachments/assets/ab5fd962-8de0-40e9-aa11-b521cc7d3f68)

**Comment by strail6** [comment]
> > > > > > 今天突然进不去面板了
> > > > > 
> > > > > 
> > > > > 查看仪表板进程还在
> > > > 
> > > > 
> > > > 这个要发送什么命令呀
> > > 
> > > 
> > > ps ux| grep nezha 看看。估计你是只安装了一台机器，无法多主机相互保活。
> > 
> > 
> > strail 43349 0.0 0.0 432 256 1430 RN+ 15:06 0:00.00 grep nezha 显示这个
> 
> 那说明你服务挂了, 你可以参考参考我的 第1, 3条是我跑了两个agent 第2条是面板 第4条是当前的查询指令
> 
> ![image](https://private-user-images.githubusercontent.com/179740367/397764601-ab5fd962-8de0-40e9-aa11-b521cc7d3f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDQ0NTgsIm5iZiI6MTczNDcwNDE1OCwicGF0aCI6Ii8xNzk3NDAzNjcvMzk3NzY0NjAxLWFiNWZkOTYyLThkZTAtNDBlOS1hYTExLWI1MjFjYzdkM2Y2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxNDE1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzE0NmYyYjRiYTE5NWNiNjk1ZjZhYTliNTI1MzA2MWRiYjRiZTQ3MzQzNzFjNTI2MDU0NjI4YjJkYTQ1NmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GYHKfFmupV67_kLHjiw6LbApS0hN6Z04M2s6gFiZ2ug)

好的吧，有时候又会自动好起来

**Comment by vfhky** [comment]
说明是crontab还没有被删除，所以还能够重新拉起探针进程

**Comment by strail6** [comment]
> 说明是crontab还没有被删除，所以还能够重新拉起探针进程

如果要删除 重新创建要发什么命令呀
