### ISSUE TITLE
安装过程中报错 v1版本 

### ISSUE THREAD

**Issue by kandyhe** [vfhky/serv00_ct8_nezha#9]
WARNING: The script qiniupy is installed in '/home/kook2/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
duplicity 3.0.0 requires atom, which is not installed.
duplicity 3.0.0 requires azure-storage-blob, which is not installed.
duplicity 3.0.0 requires boxsdk[jwt], which is not installed.
duplicity 3.0.0 requires gdata-python3, which is not installed.
duplicity 3.0.0 requires google-api-python-client, which is not installed.
duplicity 3.0.0 requires google-auth-oauthlib, which is not installed.
duplicity 3.0.0 requires jottalib, which is not installed.
duplicity 3.0.0 requires keyring, which is not installed.
duplicity 3.0.0 requires mediafire, which is not installed.
duplicity 3.0.0 requires megatools, which is not installed.
duplicity 3.0.0 requires pydrive2, which is not installed.
duplicity 3.0.0 requires pyrax, which is not installed.
duplicity 3.0.0 requires python-gettext>=5.0, which is not installed.
duplicity 3.0.0 requires python-keystoneclient, which is not installed.
duplicity 3.0.0 requires python-swiftclient, which is not installed.
duplicity 3.0.0 requires requests-oauthlib, which is not installed.
fabric 3.2.2 requires deprecated>=1.2, which is not installed.
duplicity 3.0.0 requires chardet<3.10, but you have chardet 5.2.0 which is incompatible.
duplicity 3.0.0 requires cryptography==3.4.8, but you have cryptography 42.0.8 which is incompatible.
duplicity 3.0.0 requires urllib3<1.26, but you have urllib3 1.26.18 which is incompatible.

**Comment by vfhky** [comment]
之前有安装过其它python项目吗？

**Comment by kandyhe** [comment]
> 之前安装过其他python项目吗？

我找台干净的机器 试下吧 。

**Comment by vfhky** [comment]
> > 之前安装过其他python项目吗？
> 
> 我找台干净的机器 试下吧 。

嗯，报错信息看着是依赖的Python包冲突
